spring:
  application:
    name: RoomBookingService

  datasource:
    username: root
    password: root@123
    url: jdbc:mysql://localhost:3306/roomService
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

